name: Build Win32/x64 with all deps (Release)

# triggers:
on:
  # use push only when debugging this workflow
  #push:
  # run this action when kicked off manually
  workflow_dispatch:
  # when a tag or branch created
  create:
  # published releases get checked
  release:
    types: [published]

jobs:
  #call-workflow-build-win32:
    #uses: ./.github/workflows/workflow-rebuild-all-deps.yml
    #with:
      #platform-arch: Win32

  call-workflow-build-x64:
    #needs: call-workflow-build-win32
    uses: ./.github/workflows/workflow-rebuild-all-deps.yml
    with:
      platform-arch: x64
