name: Reusable - Rebuild All Libs
# This reusable workflow rebuilds all binary dependencies. While you can pass in a build-config,
# only 'Release' configuration is supported because all libraries are built in release configuration.

# NOTE: We don't replace any header files or anything else, ONLY binaries. If there's a broken build,
# it might be due to source issues that you need to fix in the repo.

on:
  workflow_call:
    inputs:
      platform-arch:
        required: true
        type: string

      build-config:
        required: false
        type: string
        default: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code with all Submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies (CMake, pkg-configlite)
      shell: powershell
      run: |
        choco install pkgconfiglite cmake --installargs "ADD_CMAKE_TO_PATH=System" -y
        echo "C:\\Program Files (x86)\\pkgconfiglite\\bin" >> $env:GITHUB_PATH

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        # Pin to Visual Studio 2019
        vs-version: '[16.0,17.0)'
        msbuild-architecture: ${{ inputs.platform-arch }}

    - uses: ./.github/actions/setup-wix

    - uses: ./.github/actions/bin-cache

    - uses: ./.github/actions/build-solution
      with:
        platform-arch: ${{ inputs.platform-arch }}
        build-config: ${{ inputs.build-config }}

    - uses: ./.github/actions/upload-some-artifacts
      with:
        platform-arch: ${{ inputs.platform-arch }}
        build-config: ${{ inputs.build-config }}
